### ISSUE TITLE
Getting error with angularv10

### ISSUE THREAD

**Issue by chandrakanthi07** [K-Adam/ngx-loading-spinner#4]
Property 'hide' does not exist on type 'NgxLoadingSpinnerModule'.
I have installed versions 1.8 and 1.9, both are giving same error.
Please help

**Comment by K-Adam** [comment]
Hi!

I updated the library to Angular 10, but I think that you get the error for a different reason:

The `show` and `hide` methods are defined on the service, not on the module. You should import `NgxLoadingSpinnerService` where you would like to use it.

Please follow the **Setup** and **Use** parts of the readme. `NgxLoadingSpinnerModule` will be imported in your main module, and the `NgxLoadingSpinnerService`  will be used as a dependency of a component or service.

See the [example project](https://github.com/K-Adam/ngx-loading-spinner/tree/master/projects/spinner-test/src/app) for a working demo.

If you still get the error, please provide an example source code, where the error is thrown.
